version: "3"
services:
  pytouch:
    build:
     context: ./envs
     dockerfile: Dockerfile
    image: pytouch:1.0
    container_name: pytouch
    volumes:
      - ".:/home/pytouch"
    ports:
      - "8888:8888"
    privileged: true
    restart: unless-stopped
    command: jupyter lab 
